
Table roles {
  idRol int [pk, increment]
  nombre varchar(50) [not null, unique]
  fecha_registro datetime 
  fecha_mod timestamp
}

Table permisos {
  idPermisos bigint(20)
  nombre varchar(100)
  descripcion varchar(255) 
  modulo varchar(100)
  activo tinyint(1)
  fecha_registro datetime
  fecha_mod datetime
}

Table rol_permiso {
  id bigint(20) 
  idRoles int(11) [not null, ref: > roles.idRol]
  idPermisos bigint(20) [not null, ref: > permisos.idPermisos]
  activo tinyint(1)
  fecha_registro datetime
}

Table usuario {
  idusuario int [pk, increment]
  nombre varchar(255) [not null]
  nombre_usuario varchar(255) [not null, unique]
  password varchar(255) [not null]
  activo boolean [default: true]
  idRol int [not null, ref: > roles.idRol]
  telefono varchar(20)
  fecha_registro datetime 
  fecha_mod datetime
}

Table clientes {
  idclientes int [pk, increment]
  nombre_razon_social varchar(255) [not null]
  nit varchar(20) [null]
  tipo_cliente varchar(20) [null]
  limite_credito decimal(12,2) [null]
  saldo_actual decimal(12,2) [null]
  estado tinyint(1) [null]
  fecha_registro datetime [null]
  fecha_mod datetime [null] 
  usuario_idusuario  int [not null, ref: > usuario.idusuario]
}  

Table categoria { 
  idcategoria int [pk, increment]
  nombre varchar(255) [not null]
  slug varchar(255) [not null]
  imagen_url varchar(255) [not null]
  activo tinyint(1) [null] 
  descripcion varchar(255) [null]
  fecha_registro datetime [null]
  fecha_mod datetime [null]
  usuario_idusuario  int [not null, ref: > usuario.idusuario]
}

Table presentacion {
  idPresentacion int [pk, increment]
  nombre_presentacion varchar(50) [null]
  abreviatura varchar(10) [null]
  activo tinyint(1) [null] 
  descripcion varchar(255) [null]
  fecha_registro datetime [null]
  fecha_mod datetime [null]
  usuario_idusuario  int [not null, ref: > usuario.idusuario]
}

Table proveedores {
  idProveedores int [pk, increment]
  razon_social varchar(255) [null]
  nit_rut varchar(255) [null]
  direccion varchar(255) [null]
  fecha_registro datetime [null]
  fecha_mod datetime [null]
  user_mod int [not null, ref: > usuario.idusuario]
  estado tinyint(1) [null] 
} 

Table productos {
  idproductos int [pk, increment]
  codigo_barras varchar(255) [null]
  codigo_producto_proveedor varchar(45) [null]
  nombre varchar(255) [null]
  descripcion_corta varchar(255) [null]
  descripcion_larga varchar(255) [null]
  marca varchar(255) [null]
  imagen_url varchar(255) [null]
  activo_catalogo tinyint(1) [null] 
  estado_producto tinyint(1) [null] 
  categoria_idcategoria int [not null, ref: > categoria.idcategoria]
  Presentacion_idPresentacion int [not null, ref: > presentacion.idPresentacion]
  Proveedores_idProveedores int [not null, ref: > proveedores.idProveedores]
  usuario_idusuario int [not null, ref: > usuario.idusuario]
  fecha_registro datetime [null]
  fehca_mod datetime [null] 
}

Table sucursales  {
  idSucursales int [pk, increment]
  nombre varchar(100) [not null]
  direccion varchar(255) [null]
  ciudad varchar(100) [null]
  celular varchar(20) [null]
  activo tinyint(1) [null] 
  fecha_registro datetime [not null]
  fecha_mod datetime [not null]
  usuario_idusuario int [not null, ref: > usuario.idusuario]
}
  
Table inventario_sucursal {
  idInventario_sucursal int [pk, increment]
  stock_actual decimal  (12,2)
  Stock_minimo decimal  (12,2)
  ubicacion_pasillo varchar(20) [null]
  sucursales_idSucursales int [not null, ref: > sucursales.idSucursales]
  productos_idproductos int [not null, ref: > productos.idproductos]
  fecha_registro datetime
  fecha_mod datetime
  usuario_idusuario int [not null, ref: > usuario.idusuario]
 }

Table compras {
  idcompras int [pk, increment]
  numero_factura_prov varchar(50) [not null]
  total_compra decimal  (12,2)
  fecha_compra datetime
  estado_pago varchar(45) [not null]
  fecha_limite_pago date
  Proveedores_idProveedores int [not null, ref: > proveedores.idProveedores]
  sucursales_idSucursales int [not null, ref: > sucursales.idSucursales]
  fecha_registro datetime
  fecha_mod datetime
  usuario_idusuario int [not null, ref: > usuario.idusuario]
}

Table compras_detalle {
  idcompas_detalle int [pk, increment]
  catidad decimal  (12,2)
  costo_unitario  decimal(12,2)
  compras_idcompras int [not null, ref: > compras.idcompras]
  productos_idproductos int  [not null, ref: > productos.idproductos]
  fecha_registro datetime
  fecha_mod datetime
}

Table precio_compra_producto {
  idprecio_compra_producto int [pk, increment]
  precio_compra decimal (12,2)
  productos_idproductos int(11) [not null, ref: > productos.idproductos]
  Proveedores_idProveedores int(11) [not null, ref: > proveedores.idProveedores]
  fecha_registro datetime
  fecha_mod datetime
  usuario_idusuario int(11) [not null, ref: > usuario.idusuario]
}

Table precio_venta_producto {
  idprecio_venta_producto  int [pk, increment]
  tipo_cliente varchar(45)
  precio_venta decimal(12,0)
  cantidad_minima decimal(12,0) 
  limite_descuento varchar(45)
  productos_idproductos int(11) [not null, ref: > productos.idproductos]
  fecha_registro datetime
  fecha_mod datetime
  usuario_idusuario int(11) [not null, ref: > usuario.idusuario]
}

Table ventas {
  idventas int [pk, increment]
  metodo_pago varchar(100) [null]
  tipo_pago varchar(100) [null]
  pago_total decimal(12,2)
  metodo_entrega varchar(100) [null]
  estado_venta varchar(100) [null]
  clientes_idclientes int [not null, ref: > clientes.idclientes] 
  Sucursales_idSucursales int [not null, ref: > sucursales.idSucursales]

  fecha_registro datetime
  fecha_mod datetime
  usuario_idusuario int [not null, ref: > usuario.idusuario]
}

Table detalle_venta {
  iddetalle_venta int [pk, increment]
  cantidad decimal(12,2)
  precio_venta_producto varchar(45)
  descuento varchar(45)
  ventas_idventas int(11) [not null, ref: > ventas.idventas]
  Presentacion_idPresentacion int(11) [not null, ref: > presentacion.idPresentacion]
  productos_idproductos int(11) [not null, ref: > productos.idproductos]
  fecha_registro datetime
  fecha_mod datetime

}




